  
version: '3'

services:
  backend:
    build: ./backend
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.simplebfback.rule=Host(`simplebf.caue.ga`) && PathPrefix(`/doc/api`)
      #### stripprefix for dashboard
      - traefik.http.routers.simplebfback.middlewares=simplebfbackmid
      - traefik.http.middlewares.simplebfbackmid.stripprefix.prefixes=/doc/api
      - traefik.http.routers.simplebfback.tls.certresolver=letsencryptresolver
      - traefik.http.routers.simplebfback.tls=true
      - traefik.http.routers.simplebfback.entrypoints=websecure
      # if you have multiple ports exposed on the service, specify port in the web-secure service
      - traefik.http.services.simplebfback.loadbalancer.server.port=3333

  frontend:
    build: ./frontend
    networks:
    - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.simplebffront.rule=Host(`simplebf.caue.ga`) && PathPrefix(`/doc`)
      #### stripprefix for dashboard
      - traefik.http.routers.simplebffront.middlewares=simplebffrontmid
      - traefik.http.middlewares.simplebffrontmid.stripprefix.prefixes=/doc
      - traefik.http.routers.simplebffront.tls.certresolver=letsencryptresolver
      - traefik.http.routers.simplebffront.tls=true
      - traefik.http.routers.simplebffront.entrypoints=websecure
      # if you have multiple ports exposed on the service, specify port in the web-secure service
      - traefik.http.services.simplebffront.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true